### ISSUE TITLE
Make GSA-Database a submodule of GSAMain

### ISSUE THREAD

**Issue by dadamsncsa** [nanoMFG/GSAMain#167]
## Description
- [x] Rename the GSA-Database "gresq" package to: "grdb" or something...
- [x] Add GSA-Database as a submodule to GSAMain.
- [x] Switch imports in GSAMain to use the schemas installed with GSA-Database:
 `gresq.database -> grdb.database.v_1_1_0` : status quo with `grdb` instead of `gresq`
- [x] Remove GSAMain's `src/gresq/database` package

## References
https://github.blog/2016-02-01-working-with-submodules/  
https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by AagamShah97** [comment]
Workflow for moving from old schema to new schema in GSAMain:

- [ ] Add GSA_Database as a submodule to GSAMain
- [ ] Create 2 packages inside `src` {for example, called `gresq-old` and `gresq-new`} 
- [ ] Use gresq-old for the Query and the Submit tool from GSA-Database instead of the local version of the schema
- [ ] Shift from gresq-old to gresq-new in the Query tool
- [ ] Shift from gresq-old to gresq-new in the Submit tool
